site_name: Pixel&Wood Computing Science Tuition

nav:
    - Home: 'index.md'
    - S1:
      - Home: 'Homepages/2.0_S1_Home.md'
      - Turtle Programming: 'Levels/BGE/S1/Turtle_Programming/1.0_Home.md'
      - Turtle Programming1: 'Levels/BGE/S1/Turtle_Programming/test.md'
      - Hidden Tabs:
        - Introducing the Turtle: 'Levels/BGE/S1/Turtle_Programming/2.0_Introducing_the_Turtle.md'
        - Movement and Colour: 'Levels/BGE/S1/Turtle_Programming/3.0_Movement_and_Colour.md'
    - S2:
      - Home: 'Homepages/3.0_S2_Home.md'
      - Python Programming: 'Levels/BGE/S2/Python_Programming/1.0_Homepage.md'
        #- Introduction to Python: 'BGE/S2/Python_Programming/1.0_Intro_to_Python.md'
        #- Extra Credit Tasks: 'BGE/S2/Python_Programming/Extra_Credit_Tasks.md'
    - S3: 
      - Home: 'Homepages/4.0_S3_Home.md'
      - MakeCode Arcade: 
        - Space Invaders: 'Levels/BGE/S3/Makecode Arcade/Space_Invaders/space_invaders_index.md'

      - Hidden Tabs:
        - Lesson Tiles: 'Levels/BGE/S3/Makecode Arcade/Space_Invaders/lessons.md'
        - 01 - Setting up the Player: 'Levels/BGE/S3/Makecode Arcade/Space_Invaders/1.0_Setting_up_the_Player.md'
        - 02 - Shooting Lasers: 'Levels/BGE/S3/Makecode Arcade/Space_Invaders/2.0_Shooting_Lasers.md'
        - 03 - Adding Enemies: 'Levels/BGE/S3/Makecode Arcade/Space_Invaders/3.0_Adding_Enemies.md'
        - 04 - Spawning Enemies: 'Levels/BGE/S3/Makecode Arcade/Space_Invaders/4.0_Spawning_Enemies.md'
        - 05 - Adding the Bonus: 'Levels/BGE/S3/Makecode Arcade/Space_Invaders/5.0_Adding_the_Bonus.md'
    - National 4/5 Computing Science:
      - " ": 'Homepages/5.0_L5_Home.md'
      - Unit 1 - Software Design and Development: 
        - Development Methodologies: 'Levels/Senior_Phase/Unit_1_SDD/1.0_Development_Methodologies/L5/5.0_Home.md'
        - Analysis: 'Levels/Senior_Phase/Unit_1_SDD/2.0_Analysis/L5/5.0_index.md'
        - Design: 'Levels/Senior_Phase/Unit_1_SDD/3.0_Design/L5/5.0_index.md'
        - Software Implementation: 'Levels/Senior_Phase/Unit_1_SDD/4.0_Software_Implementation/L5/5.0_Home.md'
        - Testing: 'Levels/Senior_Phase/Unit_1_SDD/5.0_Testing/L5/5.0_Home.md'
        - Evaluation: 'Levels/Senior_Phase/Unit_1_SDD/6.0_Evaluation/L5/5.0_Home.md'
      - Unit 2 - Computer Systems:
        - Data Representation: 'Levels/Senior_Phase/Unit_2_CS/1.0_Data_Representation/L5/5.0_Home.md'
        - Computer Architecture: 'Levels/Senior_Phase/Unit_2_CS/2.0_Computer_Architecture/L5/5.0_Home.md'
        - Security and Encryption: 'Levels/Senior_Phase/Unit_2_CS/3.0_Security_and_Encryption/L5/5.0_Home.md'
      - Unit 3 - Database Design and Development:
        - Database Structure: 'Levels/Senior_Phase/Unit_3_DDD/1.0_Database_Structure/L4|5|6|7/4.0_index.md'
        - Analysis: 'Levels/Senior_Phase/Unit_3_DDD/2.0_Analysis/L5/5.0_index.md'
      - Unit 4 - Web Design and Development:
        - Div Class and Div ID: 'Levels/Senior_Phase/Unit_4_WDD/Div_Class_Div_ID.md'

      - Hidden Tabs:
        - Input and Output: 'Levels/Senior_Phase/Unit_1_SDD/4.0_Software_Implementation/L5/5.1_Input_and_Output.md'
        - Variables and Data Types: 'Levels/Senior_Phase/Unit_1_SDD/4.0_Software_Implementation/L5/5.2_Variables_and_Data_Types.md'
        - Arrays: 'Levels/Senior_Phase/Unit_1_SDD/4.0_Software_Implementation/L5/5.3_Arrays.md'
        - Simple Conditional Statements: 'Levels/Senior_Phase/Unit_1_SDD/4.0_Software_Implementation/L5/5.4_Simple_Conditional_Statements.md'
        - Complex Conditional Statements: 'Levels/Senior_Phase/Unit_1_SDD/4.0_Software_Implementation/L5/5.5_Complex_Conditional_Statements.md'
        - Fixed Loops(for): 'Levels/Senior_Phase/Unit_1_SDD/4.0_Software_Implementation/L5/5.6_Fixed_Loops_(for).md'
        - Conditional Loops(while): 'Levels/Senior_Phase/Unit_1_SDD/4.0_Software_Implementation/L5/5.7_Conditional_Loops_(while).md'
        - Pre-Defined Functions: 'Levels/Senior_Phase/Unit_1_SDD/4.0_Software_Implementation/L5/5.8_Pre_Defined_Functions.md'
        - Traversing a 1D Array: 'Levels/Senior_Phase/Unit_1_SDD/4.0_Software_Implementation/L5/5.9_Traversing_a_1d_Array.md'
        - Running Total within a Loop: 'Levels/Senior_Phase/Unit_1_SDD/4.0_Software_Implementation/L5/5.10_Running_Total_Within_a_Loop.md'
        - Input Validation: 'Levels/Senior_Phase/Unit_1_SDD/4.0_Software_Implementation/L5/5.11_Input_Validation.md'
        - Data Types and Structures: 'Levels/Senior_Phase/Unit_1_SDD/3.0_Design/L5/5.1_Data_Types_and_Structures.md'
        - Structure Diagrams: 'Levels/Senior_Phase/Unit_1_SDD/3.0_Design/L5/5.2_Structure_Diagrams.md'
        - Flowcharts: 'Levels/Senior_Phase/Unit_1_SDD/3.0_Design/L5/5.3_Flowcharts.md'
        - Pseudocode: 'Levels/Senior_Phase/Unit_1_SDD/3.0_Design/L5/5.4_Pseudocode.md'
    - Higher Computing Science:
      - " ": 'Homepages/6.0_L6_Home.md'
      - Unit 1 - Software Design and Development:
        - Development Methodologies: 'Levels/Senior_Phase/Unit_1_SDD/1.0_Development_Methodologies/L6/6.0_index.md'
        - Analysis: 'Levels/Senior_Phase/Unit_1_SDD/2.0_Analysis/L6/6.0_index.md'
        - Design: 'Levels/Senior_Phase/Unit_1_SDD/3.0_Design/L6/6.0_index.md'
        - Implementation: 'Levels/Senior_Phase/Unit_1_SDD/4.0_Software_Implementation/L6/6.0_index.md'
      - Unit 3 - Database Design and Development:
        - Analysis: 'Levels/Senior_Phase/Unit_3_DDD/2.0_Analysis/L6/6.0_index.md'
      - Higher Hidden Tabs:
        - Analysis: 'Levels/Senior_Phase/Unit_1_SDD/2.0_Analysis/L6/6.0_index.md'
        - Structure Diagrams: 'Levels/Senior_Phase/Unit_1_SDD/3.0_Design/L6/6.1_Structure_Diagrams.md'
        - Software Implementation: 'Levels/Senior_Phase/Unit_1_SDD/4.0_Software_Implementation/L6/6.0_index.md'
        - Parallel 1D Arrays: 'Levels/Senior_Phase/Unit_1_SDD/4.0_Software_Implementation/L6/6.1_Parallel_1D_Arrays.md'
        - Working with Records: 'Levels/Senior_Phase/Unit_1_SDD/4.0_Software_Implementation/L6/6.2_Records.md'
        - Arrays of Records: 'Levels/Senior_Phase/Unit_1_SDD/4.0_Software_Implementation/L6/6.3_Arrays_of_Records.md'
        - Parameter Passing: 'Levels/Senior_Phase/Unit_1_SDD/4.0_Software_Implementation/L6/6.4_Parameter_Passing.md'
        - Scope of Variables: 'Levels/Senior_Phase/Unit_1_SDD/4.0_Software_Implementation/L6/6.5_Scope_of_Variables.md'
        - Sub-programs(Procedures): 'Levels/Senior_Phase/Unit_1_SDD/4.0_Software_Implementation/L6/6.6_Sub-Programs_(Procedures).md'
        - Sub-programs(Functions): 'Levels/Senior_Phase/Unit_1_SDD/4.0_Software_Implementation/L6/6.7_Sub-Programs_(Functions).md'
        - Pre-defined Functions: 'Levels/Senior_Phase/Unit_1_SDD/4.0_Software_Implementation/L6/6.8_Pre-Defined_Functions.md'
        - File Handling(.csv): 'Levels/Senior_Phase/Unit_1_SDD/4.0_Software_Implementation/L6/6.9_File_Handling(.csv).md'
        - File Handling(.txt): 'Levels/Senior_Phase/Unit_1_SDD/4.0_Software_Implementation/L6/6.10_File_Handling(.txt).md'
        - Algorithms(Linear Searching): 'Levels/Senior_Phase/Unit_1_SDD/4.0_Software_Implementation/L6/6.11_Algorithms_(Linear_Search).md'
        - Algorithms(Finding Min and Max): 'Levels/Senior_Phase/Unit_1_SDD/4.0_Software_Implementation/L6/6.12_Algorithms_(Finding_Min_and_Max).md'
        - Algorithms(Count Occurances): 'Levels/Senior_Phase/Unit_1_SDD/4.0_Software_Implementation/L6/6.13_Algorithms_(Count_Occurances).md'
    - Advanced Higher Computing Science: 
      - Home: 'Homepages/7.0_L7_Home.md'
      - Unit 1 - Software Development:
        - Analysis: 'Levels/Senior_Phase/Unit_1_SDD/2.0_Analysis/L7/7.0_index.md'
        - Software Implementation: 'Levels/Senior_Phase/Unit_1_SDD/4.0_Software_Implementation/L7/7.0_index.md'
      - Hidden Tabs:
        - Feasability Studies: 'Levels/Senior_Phase/Unit_1_SDD/2.0_Analysis/L7/7.1_Feasability_Studies.md'
        - Project Planning: 'Levels/Senior_Phase/Unit_1_SDD/2.0_Analysis/L7/7.6_Project_Planning.md'
        - UML - Use Case Diagrams : 'Levels/Senior_Phase/Unit_1_SDD/2.0_Analysis/L7/7.7_UCD.md'
        - Economic: 'Levels/Senior_Phase/Unit_1_SDD/2.0_Analysis/L7/7.1.1_Economic.md'
        - Time: 'Levels/Senior_Phase/Unit_1_SDD/2.0_Analysis/L7/7.1.2_Time.md'
        - 2d Arrays: 'Levels/Senior_Phase/Unit_1_SDD/4.0_Software_Implementation/L7/7.1_2d_Arrays.md'
        - Insertation Sort: 'Levels/Senior_Phase/Unit_1_SDD/4.0_Software_Implementation/L7/7.15_Insertation_Sort.md'
        - Objects: 'Levels/Senior_Phase/Unit_1_SDD/4.0_Software_Implementation/L7/7.4_OOP_Object.md'
        - Objects: 'Levels/Senior_Phase/Unit_1_SDD/4.0_Software_Implementation/L7/7.4_OOP_Object.md'
        - Python and Databases: 'Levels/Senior_Phase/Unit_1_SDD/4.0_Software_Implementation/L7/5.1-SQLite-with-Python.md'

markdown_extensions:
      - admonition
      - pymdownx.details
      - def_list
      - pymdownx.critic
      - pymdownx.caret
      - pymdownx.keys
      - pymdownx.mark
      - pymdownx.tilde
      - attr_list
      - md_in_html    
      - pymdownx.emoji:
          emoji_index: !!python/name:material.extensions.emoji.twemoji
          emoji_generator: !!python/name:material.extensions.emoji.to_svg
      - pymdownx.superfences
      - pymdownx.tabbed:
          alternate_style: true
      - pymdownx.highlight:
          use_pygments: true
          anchor_linenums: true
          line_spans: __span
          pygments_lang_class: true
      - pymdownx.inlinehilite
      - pymdownx.snippets
      
theme:
  name: material
  font:
    text: Quicksand
  palette: 
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple

    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange
  icon:
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left
  features:
    - content.code.copy
    - content.code.annotate
    - navigation.tabs.sticky
    - navigation.top
    - navigation.indexes 
    - navigation.path
    #- navigation.footer
    - navigation.tabs
#plugins:
  #- glightbox

copyright: Copyright &copy; 2025 Pixel&Wood Computer Science Tuition

extra_css:
  - Styles/extra.css

extra_javascript:
  - scripts/extra.js
    

